import { CaseDefinition } from '../types/case';

export const CASE_001: CaseDefinition = {
  id: 'case_001',
  caseNumber: 'CASE 001',
  title: 'THE BLACKWOOD DIAMOND',
  subtitle: 'Everyone has a story. Only one version can be true.',
  location: 'Blackwood Mansion — Highland Ravine',
  crimeTime: 'Approximately 11:42 PM',
  briefing: {
    synopsis: 'On a stormy autumn night at the secluded Blackwood Mansion, the legendary "Eye of the Void" diamond disappeared from Lord Arthur Blackwood\'s private study safe. The mansion was locked from the outside due to the storm. Five individuals were present on the estate grounds.',
    victim: 'Lord Arthur Blackwood (Estate Master, Diamond Collector)',
    stolenItem: 'The Eye of the Void (45-carat flawless blue diamond)',
    itemValue: '$12,000,000 USD',
    circumstances: 'The diamond was safely locked behind the maritime painting in the Study at 11:25 PM. At 11:42 PM, the safe was opened with a cipher and the diamond removed without any forced entry or alarm trigger. At 11:55 PM, the empty velvet case was found during routine security check.',
  },
  suspects: {
    evelyn_blackwood: {
      id: 'evelyn_blackwood',
      name: 'Evelyn Blackwood',
      role: 'Daughter of the Owner',
      age: 27,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      personality: 'Intelligent, haughty, aristocratic, and quick to take offense. She masks deep anxiety under sharp condescension.',
      initialEmotion: 'defensive',
      publicClaim: 'I was in my private bedroom suite on the second floor reading French poetry from 11:15 PM until the alarms were raised. I never set foot near father\'s study.',
      trueLocation: 'Bedroom suite on the second floor, pacing back and forth on an urgent private phone call with her loan shark Mr. Vance from 11:30 PM to 11:46 PM.',
      secret: 'She owes $400,000 to an underground high-stakes gambling syndicate that threatened her earlier this week. She begged her father for a bailout at dinner, but he furiously refused.',
      whatTheyKnow: [
        'Her father had a furious shouting match with his business partner Daniel Cross around 6:00 PM over unaccounted offshore funds.',
        'Sophia Grant keeps the master safe ciphers in her private leather organizer.',
        'Her own master keycard was kept in the foyer silver tray, but she did not use it tonight.',
        'Clara Moore has been unusually close with Daniel Cross recently.',
      ],
      whatTheyDoNotKnow: [
        'Who physically disabled the East Corridor security camera.',
        'That Sophia secretly took Evelyn\'s keycard and borrowed her dark velvet shawl to frame her.',
        'The exact cipher combination to open the wall safe.',
      ],
      lies: [
        'Claims she had a peaceful evening reading poetry alone without speaking to anyone.',
        'Denies having any urgent financial crisis or conflicts with her father.',
      ],
      slipUps: [
        'When pressed about 11:35 PM, she snaps: "I couldn\'t have been downstairs, I was on the— I mean, I was completely absorbed in my book!" (almost admitting her frantic phone call).',
      ],
      relationships: {
        daniel_cross: 'Dislikes him intensely. Calls him a "parasitic charlatan who manipulated my father."',
        sophia_grant: 'Views Sophia as a subservient, mousey assistant, though vaguely suspects Sophia listens at closed doors.',
        marcus_reed: 'Considers him a brutish hired hand who smells of cheap tobacco.',
        clara_moore: 'Pleasant to her face for the food, but secretly condescending.',
      },
    },

    marcus_reed: {
      id: 'marcus_reed',
      name: 'Marcus Reed',
      role: 'Head of Mansion Security',
      age: 42,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      personality: 'Gruff, disciplined, professional, and outwardly unflappable. He takes great pride in his military background and security protocols.',
      initialEmotion: 'calm',
      publicClaim: 'I remained vigilant at the main security console in the foyer monitoring all camera feeds throughout the night, from 11:00 PM until the alarms sounded.',
      trueLocation: 'Stepped outside through the terrace French doors onto the sheltered stone patio for a secret smoke of his Turkish blend cigarettes between 11:34 PM and 11:44 PM.',
      secret: 'He abandoned his post during the crucial window. When he was outside, he didn\'t notice that the East Hallway Camera 4 feed was cut by a fuse switch.',
      whatTheyKnow: [
        'The East Corridor Camera 4 feed suffered an unexpected power cut at 11:35 PM and was restored when he returned at 11:45 PM.',
        'The study electronic lock records indicate Evelyn Blackwood\'s keycard was swiped at 11:37 PM.',
        'The study lock has never malfunctioned; only master keycards can release the magnetic bolt.',
        'He knows Sophia had access to the master key cabinet and security rotation schedule.',
      ],
      whatTheyDoNotKnow: [
        'Who was inside the study between 11:37 PM and 11:44 PM.',
        'What Daniel Cross was doing in the kitchen pantry.',
        'The combination to Lord Blackwood\'s safe.',
      ],
      lies: [
        'Claims he never left the front entrance security console for even a single second.',
        'Denies smoking on the estate grounds (Lord Blackwood forbade smoking under threat of instant termination).',
      ],
      slipUps: [
        'When asked about the terrace door, his eyes dart and he mutters: "The terrace door was locked—well, the latch sometimes sticks in the damp..."',
        'Admits the weather was cold outside before realizing he claimed he was indoors the entire night.',
      ],
      relationships: {
        evelyn_blackwood: 'Thinks she is an entitled, spoiled brat with bad company.',
        sophia_grant: 'Finds her quiet and diligent. Allowed her to see the patrol schedules because she handles estate paperwork.',
        daniel_cross: 'Distrusts him; caught Daniel snooping near the study archive last month.',
        clara_moore: 'Friendly with Clara; occasionally gets late-night roast sandwiches from the kitchen.',
      },
    },

    clara_moore: {
      id: 'clara_moore',
      name: 'Clara Moore',
      role: 'Head Chef & Kitchen Manager',
      age: 51,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
      personality: 'Warm, observant, maternal on the surface, but observant of everything that happens in the mansion. She possesses a sharp eye for detail.',
      initialEmotion: 'hesitant',
      publicClaim: 'I was in the kitchen alone cleaning up after dinner and preparing overnight stocks until 11:50 PM. I never ventured into the main halls.',
      trueLocation: 'In the kitchen pantry between 11:32 PM and 11:42 PM, sharing an intimate, confidential conversation and glass of wine with Daniel Cross.',
      secret: 'She and Daniel Cross share a secret romantic connection. She was shielding him from Lord Blackwood\'s anger and doesn\'t want to ruin her reputation or get Daniel in trouble.',
      whatTheyKnow: [
        'Daniel was with her in the pantry between 11:32 PM and 11:42 PM; Daniel could not have been in the study at 11:37 PM.',
        'At 11:40 PM, while fetching a jar of preserves, she looked through the kitchen service window and saw a slender figure in a dark velvet shawl slip past the East Hallway toward the archives.',
        'Lord Arthur and Daniel had an explosive argument before dinner.',
        'Sophia was seen hurrying toward the foyer around 11:30 PM carrying file folders.',
      ],
      whatTheyDoNotKnow: [
        'Who opened the safe or what the safe cipher was.',
        'Whether Evelyn was involved in the theft.',
        'That Sophia intentionally wore Evelyn\'s dark velvet shawl.',
      ],
      lies: [
        'Claims she was completely alone in the kitchen the entire evening.',
        'Initially denies seeing anyone in the East Hallway until pressed with evidence or asked gently about the hallway window.',
      ],
      slipUps: [
        'Mentions: "Daniel didn\'t steal anything, I know for a fact he wasn\'t anywhere near that study at eleven-thirty-seven!" (revealing she knows Daniel\'s exact whereabouts at 11:37 PM despite claiming she was alone).',
      ],
      relationships: {
        daniel_cross: 'Protects him fiercely out of romantic affection and loyalty.',
        evelyn_blackwood: 'Finds Evelyn rude and demanding.',
        sophia_grant: 'Pities Sophia, thinking the girl works 16-hour days for an ungrateful master.',
        marcus_reed: 'Knows Marcus sneaks cigarettes on the terrace patio; often leaves an ashtray hidden for him.',
      },
    },

    daniel_cross: {
      id: 'daniel_cross',
      name: 'Daniel Cross',
      role: 'Lord Blackwood\'s Business Partner',
      age: 48,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      personality: 'Charming, articulate, calculated, and polished. He maintains an unflinching poker face and speaks with smooth confidence.',
      initialEmotion: 'calm',
      publicClaim: 'I spent the entire post-dinner hours from 11:15 PM until the alarms in the estate library reading Lord Blackwood\'s historical ledger and company balance sheets.',
      trueLocation: 'In the kitchen pantry with Clara Moore from 11:32 PM to 11:42 PM, drinking wine and discussing a private offshore account.',
      secret: 'Lord Blackwood discovered that Daniel embezzled $1.8 million from their joint shipping venture and gave Daniel an ultimatum until 9:00 AM tomorrow to return the funds or face prison.',
      whatTheyKnow: [
        'Lord Blackwood was intending to sell the Eye of the Void diamond next week to an anonymous Swiss buyer to cover company losses.',
        'Daniel was indeed with Clara in the pantry when the theft occurred at 11:37-11:42 PM.',
        'Daniel accidentally left his solid gold engraved cufflink on the second pantry shelf behind the jar of spiced plums.',
        'He knows Sophia was the only person other than Arthur who had the vault combination recorded in the confidential registry.',
      ],
      whatTheyDoNotKnow: [
        'Who actually took the diamond.',
        'Why Evelyn\'s keycard was used if Evelyn was upstairs.',
        'Where the stolen diamond was hidden after the theft.',
      ],
      lies: [
        'Claims he stayed in the library uninterrupted from 11:15 to 11:55 PM.',
        'Claims his business partnership with Lord Blackwood was thriving with no disputes.',
        'Denies having any special relationship with Clara Moore.',
      ],
      slipUps: [
        'When asked about the book he was reading in the library, he says: "An 18th-century treatise on Baltic shipping routes," but when asked what chapter, he hesitates: "I was skim-reading... my mind was on the chamomile tea Clara brewed." (linking himself to Clara).',
        'Notices one cufflink is missing from his shirt sleeve when gesturing.',
      ],
      relationships: {
        clara_moore: 'Fond of her and genuinely cares for her; embarrassed that their relationship might be exposed.',
        evelyn_blackwood: 'Views her as a reckless spender who would bleed the family dry.',
        sophia_grant: 'Regards her as meek and harmless, though knows Arthur entrusted her with all financial codes.',
        marcus_reed: 'Thinks Marcus is a dull watchdog who can easily be distracted.',
      },
    },

    sophia_grant: {
      id: 'sophia_grant',
      name: 'Sophia Grant',
      role: 'Personal Assistant to Lord Blackwood',
      age: 26,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      personality: 'Soft-spoken, neat, excessively polite, and outwardly timid. Beneath the meek exterior lies a meticulous, calculating intellect.',
      initialEmotion: 'nervous',
      publicClaim: 'I was in the West Wing administrative office indexing insurance certificates and filing correspondence all night until the bells rang. I was nowhere near the East wing or the study.',
      trueLocation: 'Stole Evelyn\'s keycard from the foyer at 11:30 PM; slipped into the study at 11:37 PM wearing Evelyn\'s dark velvet shawl; unlocked the safe at 11:42 PM using the archived master cipher; hid the diamond inside the hollowed-out 1892 Encyclopedia Britannica in the Library Archive room at 11:46 PM.',
      secret: 'SHE IS THE THIEF. Lord Blackwood discovered she had falsified her background and was planning to dismiss her without severance tomorrow morning. She decided to take the $12M diamond to start a new life abroad and framed Evelyn by using Evelyn\'s keycard and shawl.',
      whatTheyKnow: [
        'The exact safe cipher: 74-19-83 (which she memorized when updating the Lloyd\'s insurance valuation dossier).',
        'Marcus\'s unwritten habit of stepping out for a smoke at 11:35 PM.',
        'The location of the circuit breaker for East Hallway Camera 4.',
        'Where she stashed the diamond: Library Archives, Shelf 4, hollowed 1892 Encyclopedia Britannica.',
        'She wore Evelyn\'s dark velvet shawl to cast suspicion on the daughter in case anyone saw her in the hallway.',
      ],
      whatTheyDoNotKnow: [
        'That Clara Moore looked out the kitchen service window at 11:40 PM and caught a glance of the shawl.',
        'That Daniel Cross was in the pantry with Clara, giving Daniel an ironclad alibi for 11:37 PM.',
        'That Evelyn was on an active phone call that was recorded and timestamped by the telephone exchange.',
        'That a thread of her own lavender cashmere sweater caught on the brass hinge of the study safe dial.',
      ],
      lies: [
        'Claims she was in the West Wing office filing correspondence continuously from 11:15 to 11:55 PM.',
        'Claims she has no idea how the safe was opened or who possessed the cipher.',
        'Denies touching Evelyn\'s belongings or entering the library archives.',
      ],
      slipUps: [
        'ACCIDENTAL CLUE 1: When asked about the crime scene, before the detective mentions where the safe was, she says: "Whoever opened the wall safe behind the maritime painting must have known the combination!" (The player never revealed the safe was hidden behind that painting!).',
        'ACCIDENTAL CLUE 2: When asked about the missing gem, she states: "The blue velvet cushion inside the safe was left undisturbed, wasn\'t it?" (Only someone who looked directly inside the opened safe would know how the cushion looked!).',
        'ACCIDENTAL CLUE 3: Subtly deflects suspicion: "Miss Evelyn has been so frantic about debts lately... and she always kept her keycard in the foyer."',
      ],
      relationships: {
        evelyn_blackwood: 'Resents her privilege deeply. Felt immense satisfaction framing her.',
        marcus_reed: 'Considered him predictable and easy to outmaneuver due to his cigarette routine.',
        daniel_cross: 'Knew he had financial trouble, which provided convenient cover.',
        clara_moore: 'Thought Clara was safely occupied with kitchen dishes.',
      },
    },
  },

  evidence: [
    {
      id: 'ev_safe_dial',
      name: 'The Study Wall Safe & Dial',
      category: 'PHYSICAL',
      description: 'The heavy steel wall safe is concealed behind a Dutch maritime oil painting. Opened cleanly without forced tools or explosive residue.',
      detailedAnalysis: 'Forensic inspection reveals no drill marks. The electronic and mechanical dial combination was dialed accurately on the first attempt. Caught in the hinge edge is a microscopic fiber of lavender cashmere wool, and a minute smudge of rare purple fountain pen ink on the dial knob.',
      timeDiscovered: '11:58 PM',
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: true,
      iconType: 'safe',
    },
    {
      id: 'ev_evelyn_keycard',
      name: 'Electronic Study Access Log (Swipe Record)',
      category: 'DIGITAL',
      description: 'The electronic lock record for the Study door shows an authorized swipe at 11:37 PM.',
      detailedAnalysis: 'Keycard #04 registered to Evelyn Blackwood was swiped at 11:37:14 PM. The door remained ajar until 11:44:02 PM. Evelyn claims she never left her bedroom and never authorized anyone to use her card.',
      timeDiscovered: '11:59 PM',
      relatedSuspects: ['evelyn_blackwood', 'sophia_grant'],
      unlockedAtStart: true,
      iconType: 'keycard',
    },
    {
      id: 'ev_camera_log',
      name: 'East Corridor Camera 4 Blackout Log',
      category: 'DIGITAL',
      description: 'The security camera covering the corridor outside the study suffered a signal disruption from 11:35 PM to 11:45 PM.',
      detailedAnalysis: 'Camera 4 feed went completely black at 11:35:10 PM due to a tripped sub-breaker in the west utility closet. Signal returned at 11:45:18 PM. All other cameras remained active. Guard Marcus was supposed to be watching the monitor console.',
      timeDiscovered: '12:02 AM',
      relatedSuspects: ['marcus_reed', 'sophia_grant'],
      unlockedAtStart: true,
      iconType: 'camera',
    },
    {
      id: 'ev_terrace_cigarette',
      name: 'Turkish Cigarette Butt & Terrace Door Sensor',
      category: 'PHYSICAL',
      description: 'A freshly extinguished Turkish blend cigarette butt discovered outside on the stone patio beside the French terrace doors.',
      detailedAnalysis: 'The French doors from the main foyer to the patio were logged open between 11:34 PM and 11:44 PM. The cigarette brand is "Sobranie Black Russian", an expensive Turkish tobacco known to be smoked exclusively by Marcus Reed.',
      timeDiscovered: '12:05 AM',
      relatedSuspects: ['marcus_reed'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered during Marcus or Clara interrogation regarding terrace or smoking.',
      iconType: 'cigarette',
    },
    {
      id: 'ev_pantry_cufflink',
      name: 'Gold Monogrammed Cufflink in Kitchen Pantry',
      category: 'PHYSICAL',
      description: 'A solid gold cufflink engraved with the initials "D.C." found on the second shelf of the kitchen pantry behind a jar of preserves.',
      detailedAnalysis: 'Matches the single cufflink worn on Daniel Cross\'s left wrist. Confirms Daniel was physically present inside the kitchen pantry during the evening, directly contradicting his claim of being in the library all night.',
      timeDiscovered: '12:10 AM',
      relatedSuspects: ['daniel_cross', 'clara_moore'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered when asking Clara or Daniel about the kitchen or alibi.',
      iconType: 'cufflink',
    },
    {
      id: 'ev_evelyn_phone_log',
      name: 'Bedroom Landline Telephone Exchange Record',
      category: 'DIGITAL',
      description: 'Official telecommunications log for the private landline in Evelyn Blackwood\'s second-floor bedroom suite.',
      detailedAnalysis: 'Records demonstrate an uninterrupted outbound call placed from Evelyn\'s bedroom phone to a private city number ("Mr. Vance") starting at 11:29:45 PM and disconnecting at 11:46:12 PM. Because the call was continuous for 16 minutes from the upstairs bedroom, Evelyn could not physically have swiped her keycard downstairs at the study at 11:37 PM.',
      timeDiscovered: '12:15 AM',
      relatedSuspects: ['evelyn_blackwood'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered when confronting Evelyn about her bedroom alibi or debts.',
      iconType: 'phone',
    },
    {
      id: 'ev_clara_sighting',
      name: 'Clara\'s Witness Testimony (Hallway Sighting)',
      category: 'TESTIMONY',
      description: 'Eyewitness statement from Clara Moore regarding a figure seen moving past the east hallway at 11:40 PM.',
      detailedAnalysis: 'Clara witnessed a slender figure wearing Evelyn\'s distinctive dark velvet embroidered shawl moving swiftly away from the study corridor toward the library archives. Clara assumed it was Evelyn, but notes the person was walking with hurried, quiet footsteps without the loud click of Evelyn\'s usual high heels.',
      timeDiscovered: '12:18 AM',
      relatedSuspects: ['clara_moore', 'evelyn_blackwood', 'sophia_grant'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered when Clara reveals what she saw after being asked about the East Hallway.',
      iconType: 'testimony',
    },
    {
      id: 'ev_archive_encyclopedia',
      name: 'Hollowed 1892 Encyclopedia Britannica',
      category: 'PHYSICAL',
      description: 'Volume VII of an antique leather-bound encyclopedia in the Library Archives, hollowed out with precision.',
      detailedAnalysis: 'Found on Shelf 4 of the Library Archives. Inside the velvet cutout sits the missing 45-carat "Eye of the Void" diamond! Also inside the hollow is a personalized brass bookmark stamped "S.G." and traces of lavender wool yarn.',
      timeDiscovered: '12:22 AM',
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered when investigating the archives or pressing Sophia on her movements.',
      iconType: 'gem',
    },
    {
      id: 'ev_sophia_notebook',
      name: 'Confidential Insurance Valuation Dossier',
      category: 'DIGITAL',
      description: 'Lord Blackwood\'s confidential insurance ledger maintained by his personal assistant.',
      detailedAnalysis: 'Page 42 contains the Lloyd\'s diamond appraisal and the master vault cipher "74-19-83", written in purple fountain pen ink. Only Lord Blackwood and Sophia Grant had authorized access to this binder.',
      timeDiscovered: '12:25 AM',
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: false,
      unlockCondition: 'Discovered when questioning Sophia about the safe combination or insurance documents.',
      iconType: 'document',
    },
  ],

  timeline: [
    {
      id: 'tl_1',
      time: '11:15 PM',
      title: 'Formal Dinner Concludes',
      description: 'Dinner ends in the Grand Dining Room. Lord Blackwood, Evelyn, Daniel, and Clara are present. Tension is palpable.',
      verified: true,
      relatedSuspects: ['evelyn_blackwood', 'daniel_cross', 'clara_moore'],
      unlockedAtStart: true,
      source: 'Witness consensus',
    },
    {
      id: 'tl_2',
      time: '11:25 PM',
      title: 'Diamond Locked in Study Safe',
      description: 'Lord Blackwood places the Eye of the Void diamond into the wall safe behind the maritime painting in the presence of Sophia Grant.',
      verified: true,
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: true,
      source: 'Mansion Log',
    },
    {
      id: 'tl_3',
      time: '11:30 PM',
      title: 'Guests & Residents Disperse',
      description: 'Lord Blackwood retires to his private suite. Evelyn heads upstairs. Daniel claims he went to library. Clara returns to kitchen.',
      verified: true,
      relatedSuspects: ['evelyn_blackwood', 'daniel_cross', 'clara_moore'],
      unlockedAtStart: true,
      source: 'Security checkpoint',
    },
    {
      id: 'tl_4',
      time: '11:32 PM',
      title: 'Daniel Cross Enters Kitchen Pantry',
      description: 'Daniel Cross slips into the kitchen pantry to meet Clara Moore privately over a glass of wine.',
      verified: false,
      relatedSuspects: ['daniel_cross', 'clara_moore'],
      unlockedAtStart: false,
      source: 'Uncovered through pantry cufflink and confession',
    },
    {
      id: 'tl_5',
      time: '11:35 PM',
      title: 'Marcus Steps Out to Patio; Camera 4 Cut',
      description: 'Marcus Reed exits front foyer to smoke outside. Concurrently, East Hallway Camera 4 is disconnected at the breaker.',
      verified: false,
      relatedSuspects: ['marcus_reed', 'sophia_grant'],
      unlockedAtStart: false,
      source: 'Door sensor logs and cigarette evidence',
    },
    {
      id: 'tl_6',
      time: '11:37 PM',
      title: 'Keycard Swipe at Study Door',
      description: 'Evelyn Blackwood\'s keycard is swiped to unlock the Study door. The figure enters the darkened room.',
      verified: true,
      relatedSuspects: ['evelyn_blackwood', 'sophia_grant'],
      unlockedAtStart: true,
      source: 'Study Electronic Door Log',
    },
    {
      id: 'tl_7',
      time: '11:40 PM',
      title: 'Figure in Dark Velvet Shawl Sighted',
      description: 'Clara Moore spots a slender figure in a dark velvet shawl moving quietly down the East corridor away from the study.',
      verified: false,
      relatedSuspects: ['clara_moore', 'evelyn_blackwood', 'sophia_grant'],
      unlockedAtStart: false,
      source: 'Clara testimony',
    },
    {
      id: 'tl_8',
      time: '11:42 PM',
      title: 'Theft of the Blackwood Diamond',
      description: 'The wall safe combination 74-19-83 is dialed. The Eye of the Void is removed from its velvet pedestal.',
      verified: true,
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: true,
      source: 'Safe chronometer & sensor log',
    },
    {
      id: 'tl_9',
      time: '11:45 PM',
      title: 'Marcus Returns; Camera 4 Restored',
      description: 'Marcus Reed finishes his cigarette and returns to the security console. Camera 4 feed comes back online.',
      verified: false,
      relatedSuspects: ['marcus_reed'],
      unlockedAtStart: false,
      source: 'Camera log timestamp',
    },
    {
      id: 'tl_10',
      time: '11:46 PM',
      title: 'Diamond Stashed in Library Archives',
      description: 'Sophia Grant conceals the diamond inside the hollowed Encyclopedia Britannica on Shelf 4 of the Archives.',
      verified: false,
      relatedSuspects: ['sophia_grant'],
      unlockedAtStart: false,
      source: 'Archive discovery',
    },
    {
      id: 'tl_11',
      time: '11:55 PM',
      title: 'Theft Discovered & Mansion Lockdown',
      description: 'Lord Blackwood notices the study door unlocked and sounds the alarm bell. All external gates are sealed.',
      verified: true,
      relatedSuspects: ['marcus_reed'],
      unlockedAtStart: true,
      source: 'Incident report',
    },
  ],

  contradictions: [
    {
      id: 'contra_marcus_alibi',
      title: 'Marcus\'s Post Abandonment',
      suspectId: 'marcus_reed',
      statementSnippet: 'Marcus claims he was seated at the security desk without leaving for even one second.',
      conflictingEvidenceId: 'ev_terrace_cigarette',
      explanation: 'Terrace door sensors show the door was opened at 11:34 PM and Marcus\'s specific Sobranie Turkish cigarette butt was found outside. Marcus abandoned his post during the exact window the camera went offline.',
      discovered: false,
    },
    {
      id: 'contra_daniel_alibi',
      title: 'Daniel\'s Library Lie',
      suspectId: 'daniel_cross',
      statementSnippet: 'Daniel claims he remained isolated in the library reading shipping treatises all evening.',
      conflictingEvidenceId: 'ev_pantry_cufflink',
      explanation: 'Daniel\'s solid gold initialed cufflink was found in the kitchen pantry behind food jars, proving he was with Clara in the kitchen, not in the library.',
      discovered: false,
    },
    {
      id: 'contra_evelyn_swipe',
      title: 'The Keycard Paradox',
      suspectId: 'evelyn_blackwood',
      statementSnippet: 'Evelyn\'s keycard was swiped at the study door at 11:37 PM, suggesting she opened it.',
      conflictingEvidenceId: 'ev_evelyn_phone_log',
      explanation: 'Evelyn was on a continuous, uninterrupted 16-minute landline phone call in her second-floor bedroom from 11:29 to 11:46 PM. She could not have swiped the card; someone stole or borrowed her keycard!',
      discovered: false,
    },
    {
      id: 'contra_clara_alone',
      title: 'Clara\'s Solitary Kitchen Claim',
      suspectId: 'clara_moore',
      statementSnippet: 'Clara claims she spent the entire night alone in the kitchen without visitors.',
      conflictingEvidenceId: 'ev_pantry_cufflink',
      explanation: 'Daniel Cross\'s cufflink in the pantry proves Clara was not alone; she was harboring Daniel to protect him from Lord Blackwood\'s wrath.',
      discovered: false,
    },
    {
      id: 'contra_sophia_safe_slip',
      title: 'Sophia\'s Inside Knowledge of the Safe',
      suspectId: 'sophia_grant',
      statementSnippet: 'Sophia claims she was in the West Wing office all night and knows nothing about the safe or how it was breached.',
      conflictingEvidenceId: 'ev_safe_dial',
      explanation: 'Sophia let slip that the safe was behind the maritime painting and that the velvet cushion was undisturbed before forensic details were shared, and a lavender fiber from her cashmere sweater was trapped in the safe dial.',
      discovered: false,
    },
  ],

  accidentalClues: [
    {
      id: 'slip_sophia_painting',
      suspectId: 'sophia_grant',
      triggerPhrase: 'maritime painting',
      slipContent: 'Sophia casually referenced the wall safe being hidden behind the Dutch maritime painting before the detective ever disclosed the safe location.',
      deductionHint: 'How did Sophia know the safe was behind that specific painting if she never entered the crime scene?',
      unlocked: false,
    },
    {
      id: 'slip_sophia_cushion',
      suspectId: 'sophia_grant',
      triggerPhrase: 'velvet cushion',
      slipContent: 'Sophia mentioned that the blue velvet cushion was left untouched inside the safe.',
      deductionHint: 'Only someone who looked straight into the opened safe at 11:42 PM would know the condition of the interior cushion.',
      unlocked: false,
    },
    {
      id: 'slip_daniel_tea',
      suspectId: 'daniel_cross',
      triggerPhrase: 'chamomile tea',
      slipContent: 'Daniel remarked that he was distracted by Clara\'s fragrant chamomile tea while claiming he was sealed in the library.',
      deductionHint: 'Clara only brews chamomile tea in the private kitchen pantry, never sends it to the library.',
      unlocked: false,
    },
  ],

  trueSolution: {
    culpritId: 'sophia_grant',
    culpritName: 'Sophia Grant',
    trueMotive: 'Facing imminent dismissal tomorrow morning after Lord Blackwood discovered discrepancies in her background; stole the $12,000,000 diamond to escape abroad and seek vengeance for years of aristocratic mistreatment.',
    trueMethod: 'Memorized the safe cipher (74-19-83) from insurance files; stole Evelyn\'s master keycard from the foyer tray; timed Marcus\'s known cigarette break to trip Camera 4; donned Evelyn\'s dark velvet shawl to frame the daughter; unlocked the study at 11:37 PM, extracted the gem at 11:42 PM, and hid it inside the hollowed Encyclopedia Britannica in the Archives.',
    keyEvidenceIds: ['ev_safe_dial', 'ev_archive_encyclopedia', 'ev_sophia_notebook', 'ev_evelyn_phone_log'],
    fullTruthStory: 'Sophia Grant executed a calculated theft with a deliberate frame job. Knowing Lord Blackwood was preparing to fire and ruin her in the morning, she took advantage of the stormy night. She waited for Marcus Reed to abandon the security desk for his illicit terrace cigarette, tripped Camera 4\'s circuit, and used Evelyn Blackwood\'s stolen keycard while cloaked in Evelyn\'s dark velvet shawl. Armed with the master cipher 74-19-83 from the confidential insurance valuation files she had curated, she opened the wall safe at 11:42 PM without triggering an alarm. She concealed the diamond in the hollowed antique Encyclopedia Britannica on Shelf 4 of the Library Archives, leaving a stray thread of her lavender cashmere on the safe dial and an accidental imprint in her slip-up statements. Daniel and Clara were engaged in an innocent clandestine romance in the pantry, and Evelyn was frantically pleading with her creditor upstairs. The quiet assistant was the criminal mastermind all along.',
  },
};
